# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:gustave/animations/roam.walk/zzz/apply_frame {frame: 20}
scoreboard players add @s aj.roam.walk.frame 1