# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.gustave.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'gustave', 'function_path': 'animated_java:gustave/animations/dodge/play'}
tag @s add aj.gustave.animation.dodge.playing
scoreboard players set @s aj.dodge.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:gustave/animations/dodge/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only