# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:gustave/animations/idle.turn/stop
tag @s add mid_attack
scoreboard players set @s ex.player.move_duration 45