# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
summon minecraft:text_display ^0 ^2.25 ^0 {Tags:["aj.global.bone.body.child","aj.global.bone.body.child.locator","aj.global.bone.body.decendant","aj.global.bone.body.decendant.locator","aj.global.bone.body.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.locator3","aj.gustave.bone.body.child","aj.gustave.bone.body.child.locator","aj.gustave.bone.body.decendant","aj.gustave.bone.body.decendant.locator","aj.gustave.bone.body.tree","aj.gustave.entity","aj.gustave.locator","aj.gustave.locator.locator3","aj.gustave.node","aj.gustave.node.locator3","aj.new"]}
execute as @n[ type=minecraft:text_display, tag=aj.new, tag=aj.gustave.locator.locator3, distance=..5 ] run function animated_java:gustave/zzz/summon/as_data_entity/as_locator/locator3
data modify entity @s data.uuids.locator_locator3 set from storage aj:uuid main.out
data modify entity @s data.locators.locator3.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gustave.node.sword] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_sword set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gustave.node.right_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gustave.node.gun] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_gun set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gustave.node.left_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gustave.node.right_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gustave.node.left_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gustave.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gustave.node.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body set from storage aj:uuid main.out