# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound minecraft:block.iron_trapdoor.close
function animated_java:gustave/animations/idle.turn/stop