# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:gustave/animations/idle.turn/stop
function animated_java:gustave/animations/roam.walk/stop
function animated_java:gustave/animations/roam.run/stop