# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_sword) {transformation: [0f,0f,0f,-0.375f,0f,0f,0f,0.75f,0f,0f,0f,0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-1f,0f,0f,-0.3125f,0f,1f,0f,1.375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_gun) {transformation: [0f,0f,0f,0.4022f,0f,0f,0f,0.7533f,0f,0f,0f,0.1094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-0.999f,-0.0436f,0f,0.3125f,-0.0436f,0.999f,0f,1.375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1f,0f,0f,-0.1187f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg) {transformation: [-0.999f,0f,0.0436f,0.1188f,0f,1f,0f,0.75f,-0.0436f,0f,-0.999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"posx":-0.375,"posy":0.75,"posz":0.031262187499999955,"roty":0,"rotx":0},"locator2":{"posx":0.4022027400006695,"posy":0.7533185756011185,"posz":0.10937578125000005,"roty":0,"rotx":4.4139062980501586e-32},"locator3":{"posx":0,"posy":2.25,"posz":0,"roty":0,"rotx":0}}}