# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.gustave.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'gustave', 'function_path': 'animated_java:gustave/animations/pause_all'}
tag @s remove aj.gustave.animation.idle.turn.playing
tag @s remove aj.gustave.animation.attack.playing
tag @s remove aj.gustave.animation.aim.playing
tag @s remove aj.gustave.animation.shoot.playing
tag @s remove aj.gustave.animation.dodge.playing
tag @s remove aj.gustave.animation.block.playing
tag @s remove aj.gustave.animation.counter.playing
tag @s remove aj.gustave.animation.roam.walk.playing
tag @s remove aj.gustave.animation.roam.idle.playing
tag @s remove aj.gustave.animation.roam.run.playing