# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:gustave/animations/idle.turn/stop
function animated_java:gustave/animations/block/stop
playsound minecraft:entity.breeze.inhale master @a ~ ~ ~ 0.5 0.6