# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.gustave.root] run return 0
execute on passengers if entity @s[tag=aj.gustave.data] unless data entity @s {data:{rigHash: 'c9cf995f7ecb2e21cf3491fa931e90b8ce073958c9d0e3e7139f3d60c07a9cdd'}} on vehicle run function animated_java:gustave/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1