# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.gustave.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.gustave.animation.idle.turn.playing] run function animated_java:gustave/animations/idle.turn/zzz/on_tick
execute if entity @s[tag=aj.gustave.animation.attack.playing] run function animated_java:gustave/animations/attack/zzz/on_tick
execute if entity @s[tag=aj.gustave.animation.aim.playing] run function animated_java:gustave/animations/aim/zzz/on_tick
execute if entity @s[tag=aj.gustave.animation.shoot.playing] run function animated_java:gustave/animations/shoot/zzz/on_tick
execute if entity @s[tag=aj.gustave.animation.dodge.playing] run function animated_java:gustave/animations/dodge/zzz/on_tick
execute if entity @s[tag=aj.gustave.animation.block.playing] run function animated_java:gustave/animations/block/zzz/on_tick
execute if entity @s[tag=aj.gustave.animation.counter.playing] run function animated_java:gustave/animations/counter/zzz/on_tick
execute if entity @s[tag=aj.gustave.animation.roam.walk.playing] run function animated_java:gustave/animations/roam.walk/zzz/on_tick
execute if entity @s[tag=aj.gustave.animation.roam.idle.playing] run function animated_java:gustave/animations/roam.idle/zzz/on_tick
execute if entity @s[tag=aj.gustave.animation.roam.run.playing] run function animated_java:gustave/animations/roam.run/zzz/on_tick
execute on passengers if entity @s[tag=aj.gustave.data] run function animated_java:gustave/root/zzz/on_tick/locators_and_cameras
execute at @s on passengers run rotate @s ~ ~