# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:gustave/animations/aim/stop
function animated_java:gustave/animations/shoot/stop
function animated_java:gustave/animations/roam.idle/stop
function animated_java:gustave/animations/roam.walk/stop
function animated_java:gustave/animations/roam.run/stop