# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.new
function animated_java:global/internal/gu/convert_uuid_array_to_string
tp @s ^0 ^2.25 ^0 ~0 ~0
tag @s add character.nameplate
data merge entity @s {text:{"selector":"@p[tag=player]"}}
data merge entity @s {billboard:"center"}
data merge entity @s {teleport_duration:1}